[profile.default]
src = "src"
out = "out"
ffi = true  # 添加这行启用 FFI
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./"}]
ast = true

solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
auto_detect_solc=true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
